config/routes.rb
Rails.application.routes.draw do
  get "/", to: "workforce_applications#new"
  resources :workforce_applications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Cfa::Styleguide::Engine => "/cfa"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/workforce_application.rb
class WorkforceApplication < ApplicationRecord
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/workforce_applications_controller.rb
class WorkforceApplicationsController < ApplicationController
  before_action :set_workforce_application, only: [:show, :edit, :update, :destroy]

  # GET /workforce_applications
  def index
    @workforce_applications = WorkforceApplication.all
  end

  # GET /workforce_applications/1
  def show
  end

  # GET /workforce_applications/new
  def new
    @workforce_application = WorkforceApplication.new
  end

  # GET /workforce_applications/1/edit
  def edit
  end

  # POST /workforce_applications
  def create
    @workforce_application = WorkforceApplication.new(workforce_application_params)

    if @workforce_application.save
      redirect_to @workforce_application, notice: 'Workforce application was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /workforce_applications/1
  def update
    if @workforce_application.update(workforce_application_params)
      redirect_to @workforce_application, notice: 'Workforce application was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /workforce_applications/1
  def destroy
    @workforce_application.destroy
    redirect_to workforce_applications_url, notice: 'Workforce application was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workforce_application
      @workforce_application = WorkforceApplication.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def workforce_application_params
      params.require(:workforce_application).permit(:email, :phone_number, :household_size, :earned_income)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workforce_applications_helper.rb
module WorkforceApplicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkforceIntake</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page-wrapper">
      <section class="slab">
        <div class="grid">
          <%= yield %>
        </div>
      </section>
    </div>
  </body>
</html>

app/views/workforce_applications/_form.html.erb
<main id="main" class="form-card">
  <%= form_with(model: workforce_application, local: true, builder: Cfa::Styleguide::CfaFormBuilder) do |form| %>

    <header class="form-card__header">
      <h1 class="form-card__title">
        Tell us about yourself
      </h1>
    </header>

    <div class="form-card__content">
      <%= form.cfa_input_field(:email, "What is your email?", type: "email") %>
      <%= form.cfa_input_field(:phone_number, "What is your phone number?", type: "tel",
                               help_text: "We will send you text messages at this number.") %>
      <%= form.cfa_input_field(:household_size, "How many people do you live with and share money with?", type: "number") %>
      <%= form.cfa_input_field(:earned_income, "How much money do you make each month?", type: "number",
                               help_text: "Your best estimate is okay.", prefix: "$") %>
    </div>
    <div class="form-card__footer">
      <button type="submit" class="button button--primary">Continue <i class="icon icon-arrow_forward"></i></button>
    </div>
  <% end %>
</main>

app/views/workforce_applications/edit.html.erb
<%= render 'form', workforce_application: @workforce_application %>

app/views/workforce_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workforce Applications</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Phone number</th>
      <th>Household size</th>
      <th>Earned income</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workforce_applications.each do |workforce_application| %>
      <tr>
        <td><%= workforce_application.email %></td>
        <td><%= workforce_application.phone_number %></td>
        <td><%= workforce_application.household_size %></td>
        <td><%= workforce_application.earned_income %></td>
        <td><%= link_to 'Show', workforce_application %></td>
        <td><%= link_to 'Edit', edit_workforce_application_path(workforce_application) %></td>
        <td><%= link_to 'Destroy', workforce_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workforce Application', new_workforce_application_path %>

app/views/workforce_applications/new.html.erb
<%= render 'form', workforce_application: @workforce_application %>

app/views/workforce_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @workforce_application.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @workforce_application.phone_number %>
</p>

<p>
  <strong>Household size:</strong>
  <%= @workforce_application.household_size %>
</p>

<p>
  <strong>Earned income:</strong>
  <%= @workforce_application.earned_income %>
</p>

<%= link_to 'Edit', edit_workforce_application_path(@workforce_application) %> |
<%= link_to 'Back', workforce_applications_path %>